server:
  port: ${SERVER_PORT}

spring:
  application:
    name: Java

  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

#logging
logging:
  level:
    root: DEBUG
    org.hibernate: DEBUG
    org.springframework.data.*.*: DEBUG
    org.springframework.cache.*.*: DEBUG
    org.springframework.web.*.*: DEBUG
    org.apache: DEBUG
    com.example.api: DEBUG
    com.zaxxer.hikari: DEBUG

security:
  jwt:
    token:
      secret-key: my-secret-key
      expiration: 300000
    refresh-token:
      expiration: 604800000

http:
  auth-token-header-name: X-API-KEY
  auth-token: test123