spring:
  application:
    name: Java

  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.springframework.data.*.*: INFO
    org.springframework.cache.*.*: INFO
    org.springframework.web.*.*: INFO
    org.apache: INFO
    com.example.api: INFO
    com.zaxxer.hikari: INFO

security:
  jwt:
    token:
      secret-key: my-secret-key
      expiration: 300000

http:
  auth-token-header-name: X-API-KEY
  auth-token: test123

